// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.0
// source: proto/deck_pocket.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeckService_CreateDeck_FullMethodName = "/DeckService/CreateDeck"
	DeckService_GetDeck_FullMethodName    = "/DeckService/GetDeck"
	DeckService_AddCard_FullMethodName    = "/DeckService/AddCard"
	DeckService_EditDeck_FullMethodName   = "/DeckService/EditDeck"
	DeckService_RemoveDeck_FullMethodName = "/DeckService/RemoveDeck"
)

// DeckServiceClient is the client API for DeckService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeckServiceClient interface {
	CreateDeck(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetDeck(ctx context.Context, in *GetDeckResquest, opts ...grpc.CallOption) (*Response, error)
	AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*Response, error)
	EditDeck(ctx context.Context, in *EditCardRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveDeck(ctx context.Context, in *GetDeckResquest, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type deckServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeckServiceClient(cc grpc.ClientConnInterface) DeckServiceClient {
	return &deckServiceClient{cc}
}

func (c *deckServiceClient) CreateDeck(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DeckService_CreateDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) GetDeck(ctx context.Context, in *GetDeckResquest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DeckService_GetDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DeckService_AddCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) EditDeck(ctx context.Context, in *EditCardRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DeckService_EditDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deckServiceClient) RemoveDeck(ctx context.Context, in *GetDeckResquest, opts ...grpc.CallOption) (*ResponseMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, DeckService_RemoveDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeckServiceServer is the server API for DeckService service.
// All implementations must embed UnimplementedDeckServiceServer
// for forward compatibility.
type DeckServiceServer interface {
	CreateDeck(context.Context, *Request) (*Response, error)
	GetDeck(context.Context, *GetDeckResquest) (*Response, error)
	AddCard(context.Context, *AddCardRequest) (*Response, error)
	EditDeck(context.Context, *EditCardRequest) (*Response, error)
	RemoveDeck(context.Context, *GetDeckResquest) (*ResponseMessage, error)
	mustEmbedUnimplementedDeckServiceServer()
}

// UnimplementedDeckServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeckServiceServer struct{}

func (UnimplementedDeckServiceServer) CreateDeck(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeck not implemented")
}
func (UnimplementedDeckServiceServer) GetDeck(context.Context, *GetDeckResquest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeck not implemented")
}
func (UnimplementedDeckServiceServer) AddCard(context.Context, *AddCardRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCard not implemented")
}
func (UnimplementedDeckServiceServer) EditDeck(context.Context, *EditCardRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method EditDeck not implemented")
}
func (UnimplementedDeckServiceServer) RemoveDeck(context.Context, *GetDeckResquest) (*ResponseMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDeck not implemented")
}
func (UnimplementedDeckServiceServer) mustEmbedUnimplementedDeckServiceServer() {}
func (UnimplementedDeckServiceServer) testEmbeddedByValue()                     {}

// UnsafeDeckServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeckServiceServer will
// result in compilation errors.
type UnsafeDeckServiceServer interface {
	mustEmbedUnimplementedDeckServiceServer()
}

func RegisterDeckServiceServer(s grpc.ServiceRegistrar, srv DeckServiceServer) {
	// If the following call panics, it indicates UnimplementedDeckServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeckService_ServiceDesc, srv)
}

func _DeckService_CreateDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).CreateDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_CreateDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).CreateDeck(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_GetDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeckResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).GetDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_GetDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).GetDeck(ctx, req.(*GetDeckResquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_AddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).AddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_AddCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).AddCard(ctx, req.(*AddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_EditDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).EditDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_EditDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).EditDeck(ctx, req.(*EditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeckService_RemoveDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeckResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeckServiceServer).RemoveDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeckService_RemoveDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeckServiceServer).RemoveDeck(ctx, req.(*GetDeckResquest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeckService_ServiceDesc is the grpc.ServiceDesc for DeckService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeckService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeckService",
	HandlerType: (*DeckServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeck",
			Handler:    _DeckService_CreateDeck_Handler,
		},
		{
			MethodName: "GetDeck",
			Handler:    _DeckService_GetDeck_Handler,
		},
		{
			MethodName: "AddCard",
			Handler:    _DeckService_AddCard_Handler,
		},
		{
			MethodName: "EditDeck",
			Handler:    _DeckService_EditDeck_Handler,
		},
		{
			MethodName: "RemoveDeck",
			Handler:    _DeckService_RemoveDeck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/deck_pocket.proto",
}
