// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: proto/deck_pocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeckResquest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckResquest) Reset() {
	*x = GetDeckResquest{}
	mi := &file_proto_deck_pocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckResquest) ProtoMessage() {}

func (x *GetDeckResquest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckResquest.ProtoReflect.Descriptor instead.
func (*GetDeckResquest) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeckResquest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantidade    int32                  `protobuf:"varint,1,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Card          []*Card                `protobuf:"bytes,3,rep,name=card,proto3" json:"card,omitempty"`
	Estatistica   *Estatistica           `protobuf:"bytes,4,opt,name=estatistica,proto3" json:"estatistica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_deck_pocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

func (x *Request) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Request) GetCard() []*Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *Request) GetEstatistica() *Estatistica {
	if x != nil {
		return x.Estatistica
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantidade    int32                  `protobuf:"varint,2,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Card          []*Card                `protobuf:"bytes,4,rep,name=card,proto3" json:"card,omitempty"`
	Estatistica   *Estatistica           `protobuf:"bytes,5,opt,name=estatistica,proto3" json:"estatistica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_deck_pocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Response) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

func (x *Response) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Response) GetCard() []*Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *Response) GetEstatistica() *Estatistica {
	if x != nil {
		return x.Estatistica
	}
	return nil
}

type Card struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ID    int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Types that are valid to be assigned to CardType:
	//
	//	*Card_Pokemon
	//	*Card_Item
	//	*Card_Apoiador
	CardType      isCard_CardType `protobuf_oneof:"card_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_deck_pocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Card) GetCardType() isCard_CardType {
	if x != nil {
		return x.CardType
	}
	return nil
}

func (x *Card) GetPokemon() *Pokemon {
	if x != nil {
		if x, ok := x.CardType.(*Card_Pokemon); ok {
			return x.Pokemon
		}
	}
	return nil
}

func (x *Card) GetItem() *Item {
	if x != nil {
		if x, ok := x.CardType.(*Card_Item); ok {
			return x.Item
		}
	}
	return nil
}

func (x *Card) GetApoiador() *Apoiador {
	if x != nil {
		if x, ok := x.CardType.(*Card_Apoiador); ok {
			return x.Apoiador
		}
	}
	return nil
}

type isCard_CardType interface {
	isCard_CardType()
}

type Card_Pokemon struct {
	Pokemon *Pokemon `protobuf:"bytes,2,opt,name=pokemon,proto3,oneof"`
}

type Card_Item struct {
	Item *Item `protobuf:"bytes,3,opt,name=item,proto3,oneof"`
}

type Card_Apoiador struct {
	Apoiador *Apoiador `protobuf:"bytes,4,opt,name=apoiador,proto3,oneof"`
}

func (*Card_Pokemon) isCard_CardType() {}

func (*Card_Item) isCard_CardType() {}

func (*Card_Apoiador) isCard_CardType() {}

type Pokemon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Tipo          string                 `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Estagio       int32                  `protobuf:"varint,5,opt,name=estagio,proto3" json:"estagio,omitempty"`
	Geracao       int32                  `protobuf:"varint,6,opt,name=geracao,proto3" json:"geracao,omitempty"`
	Ps            int32                  `protobuf:"varint,7,opt,name=ps,proto3" json:"ps,omitempty"`
	Recuo         int32                  `protobuf:"varint,8,opt,name=recuo,proto3" json:"recuo,omitempty"`
	Fraqueza      string                 `protobuf:"bytes,9,opt,name=fraqueza,proto3" json:"fraqueza,omitempty"`
	Ataque        []*Ataque              `protobuf:"bytes,10,rep,name=ataque,proto3" json:"ataque,omitempty"`
	Habilidade    []*Habilidade          `protobuf:"bytes,11,rep,name=habilidade,proto3" json:"habilidade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	mi := &file_proto_deck_pocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{4}
}

func (x *Pokemon) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Pokemon) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Pokemon) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Pokemon) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Pokemon) GetEstagio() int32 {
	if x != nil {
		return x.Estagio
	}
	return 0
}

func (x *Pokemon) GetGeracao() int32 {
	if x != nil {
		return x.Geracao
	}
	return 0
}

func (x *Pokemon) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

func (x *Pokemon) GetRecuo() int32 {
	if x != nil {
		return x.Recuo
	}
	return 0
}

func (x *Pokemon) GetFraqueza() string {
	if x != nil {
		return x.Fraqueza
	}
	return ""
}

func (x *Pokemon) GetAtaque() []*Ataque {
	if x != nil {
		return x.Ataque
	}
	return nil
}

func (x *Pokemon) GetHabilidade() []*Habilidade {
	if x != nil {
		return x.Habilidade
	}
	return nil
}

type Ataque struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Dano          int32                  `protobuf:"varint,2,opt,name=dano,proto3" json:"dano,omitempty"`
	Custo         string                 `protobuf:"bytes,3,opt,name=custo,proto3" json:"custo,omitempty"`
	Efeito        string                 `protobuf:"bytes,4,opt,name=efeito,proto3" json:"efeito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ataque) Reset() {
	*x = Ataque{}
	mi := &file_proto_deck_pocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ataque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ataque) ProtoMessage() {}

func (x *Ataque) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ataque.ProtoReflect.Descriptor instead.
func (*Ataque) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{5}
}

func (x *Ataque) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Ataque) GetDano() int32 {
	if x != nil {
		return x.Dano
	}
	return 0
}

func (x *Ataque) GetCusto() string {
	if x != nil {
		return x.Custo
	}
	return ""
}

func (x *Ataque) GetEfeito() string {
	if x != nil {
		return x.Efeito
	}
	return ""
}

type Habilidade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nome          string                 `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Efeito        string                 `protobuf:"bytes,2,opt,name=efeito,proto3" json:"efeito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Habilidade) Reset() {
	*x = Habilidade{}
	mi := &file_proto_deck_pocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Habilidade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habilidade) ProtoMessage() {}

func (x *Habilidade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habilidade.ProtoReflect.Descriptor instead.
func (*Habilidade) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{6}
}

func (x *Habilidade) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Habilidade) GetEfeito() string {
	if x != nil {
		return x.Efeito
	}
	return ""
}

type Apoiador struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Efeito        string                 `protobuf:"bytes,4,opt,name=efeito,proto3" json:"efeito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Apoiador) Reset() {
	*x = Apoiador{}
	mi := &file_proto_deck_pocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apoiador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apoiador) ProtoMessage() {}

func (x *Apoiador) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apoiador.ProtoReflect.Descriptor instead.
func (*Apoiador) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{7}
}

func (x *Apoiador) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Apoiador) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Apoiador) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Apoiador) GetEfeito() string {
	if x != nil {
		return x.Efeito
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Efeito        string                 `protobuf:"bytes,4,opt,name=efeito,proto3" json:"efeito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_deck_pocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{8}
}

func (x *Item) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Item) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Item) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Item) GetEfeito() string {
	if x != nil {
		return x.Efeito
	}
	return ""
}

type Estatistica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdEstatisca   int32                  `protobuf:"varint,1,opt,name=id_estatisca,json=idEstatisca,proto3" json:"id_estatisca,omitempty"`
	Vitoria       int32                  `protobuf:"varint,2,opt,name=vitoria,proto3" json:"vitoria,omitempty"`
	Derrota       int32                  `protobuf:"varint,3,opt,name=derrota,proto3" json:"derrota,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	PontoGanho    int32                  `protobuf:"varint,5,opt,name=ponto_ganho,json=pontoGanho,proto3" json:"ponto_ganho,omitempty"`
	PontoPerdido  int32                  `protobuf:"varint,6,opt,name=ponto_perdido,json=pontoPerdido,proto3" json:"ponto_perdido,omitempty"`
	MediaPontos   int32                  `protobuf:"varint,7,opt,name=media_pontos,json=mediaPontos,proto3" json:"media_pontos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Estatistica) Reset() {
	*x = Estatistica{}
	mi := &file_proto_deck_pocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estatistica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estatistica) ProtoMessage() {}

func (x *Estatistica) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estatistica.ProtoReflect.Descriptor instead.
func (*Estatistica) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{9}
}

func (x *Estatistica) GetIdEstatisca() int32 {
	if x != nil {
		return x.IdEstatisca
	}
	return 0
}

func (x *Estatistica) GetVitoria() int32 {
	if x != nil {
		return x.Vitoria
	}
	return 0
}

func (x *Estatistica) GetDerrota() int32 {
	if x != nil {
		return x.Derrota
	}
	return 0
}

func (x *Estatistica) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Estatistica) GetPontoGanho() int32 {
	if x != nil {
		return x.PontoGanho
	}
	return 0
}

func (x *Estatistica) GetPontoPerdido() int32 {
	if x != nil {
		return x.PontoPerdido
	}
	return 0
}

func (x *Estatistica) GetMediaPontos() int32 {
	if x != nil {
		return x.MediaPontos
	}
	return 0
}

var File_proto_deck_pocket_proto protoreflect.FileDescriptor

const file_proto_deck_pocket_proto_rawDesc = "" +
	"\n" +
	"\x17proto/deck_pocket.proto\"!\n" +
	"\x0fGetDeckResquest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\"\x88\x01\n" +
	"\aRequest\x12\x1e\n" +
	"\n" +
	"quantidade\x18\x01 \x01(\x05R\n" +
	"quantidade\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12\x19\n" +
	"\x04card\x18\x03 \x03(\v2\x05.CardR\x04card\x12.\n" +
	"\vestatistica\x18\x04 \x01(\v2\f.EstatisticaR\vestatistica\"\x99\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1e\n" +
	"\n" +
	"quantidade\x18\x02 \x01(\x05R\n" +
	"quantidade\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12\x19\n" +
	"\x04card\x18\x04 \x03(\v2\x05.CardR\x04card\x12.\n" +
	"\vestatistica\x18\x05 \x01(\v2\f.EstatisticaR\vestatistica\"\x8f\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12$\n" +
	"\apokemon\x18\x02 \x01(\v2\b.PokemonH\x00R\apokemon\x12\x1b\n" +
	"\x04item\x18\x03 \x01(\v2\x05.ItemH\x00R\x04item\x12'\n" +
	"\bapoiador\x18\x04 \x01(\v2\t.ApoiadorH\x00R\bapoiadorB\v\n" +
	"\tcard_type\"\xa2\x02\n" +
	"\aPokemon\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x12\n" +
	"\x04tipo\x18\x04 \x01(\tR\x04tipo\x12\x18\n" +
	"\aestagio\x18\x05 \x01(\x05R\aestagio\x12\x18\n" +
	"\ageracao\x18\x06 \x01(\x05R\ageracao\x12\x0e\n" +
	"\x02ps\x18\a \x01(\x05R\x02ps\x12\x14\n" +
	"\x05recuo\x18\b \x01(\x05R\x05recuo\x12\x1a\n" +
	"\bfraqueza\x18\t \x01(\tR\bfraqueza\x12\x1f\n" +
	"\x06ataque\x18\n" +
	" \x03(\v2\a.AtaqueR\x06ataque\x12+\n" +
	"\n" +
	"habilidade\x18\v \x03(\v2\v.HabilidadeR\n" +
	"habilidade\"^\n" +
	"\x06Ataque\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x12\n" +
	"\x04dano\x18\x02 \x01(\x05R\x04dano\x12\x14\n" +
	"\x05custo\x18\x03 \x01(\tR\x05custo\x12\x16\n" +
	"\x06efeito\x18\x04 \x01(\tR\x06efeito\"8\n" +
	"\n" +
	"Habilidade\x12\x12\n" +
	"\x04nome\x18\x01 \x01(\tR\x04nome\x12\x16\n" +
	"\x06efeito\x18\x02 \x01(\tR\x06efeito\"c\n" +
	"\bApoiador\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x16\n" +
	"\x06efeito\x18\x04 \x01(\tR\x06efeito\"_\n" +
	"\x04Item\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x16\n" +
	"\x06efeito\x18\x04 \x01(\tR\x06efeito\"\xe3\x01\n" +
	"\vEstatistica\x12!\n" +
	"\fid_estatisca\x18\x01 \x01(\x05R\vidEstatisca\x12\x18\n" +
	"\avitoria\x18\x02 \x01(\x05R\avitoria\x12\x18\n" +
	"\aderrota\x18\x03 \x01(\x05R\aderrota\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1f\n" +
	"\vponto_ganho\x18\x05 \x01(\x05R\n" +
	"pontoGanho\x12#\n" +
	"\rponto_perdido\x18\x06 \x01(\x05R\fpontoPerdido\x12!\n" +
	"\fmedia_pontos\x18\a \x01(\x05R\vmediaPontos2X\n" +
	"\vDeckService\x12!\n" +
	"\n" +
	"CreateDeck\x12\b.Request\x1a\t.Response\x12&\n" +
	"\aGetDeck\x12\x10.GetDeckResquest\x1a\t.ResponseB\aZ\x05go/pbb\x06proto3"

var (
	file_proto_deck_pocket_proto_rawDescOnce sync.Once
	file_proto_deck_pocket_proto_rawDescData []byte
)

func file_proto_deck_pocket_proto_rawDescGZIP() []byte {
	file_proto_deck_pocket_proto_rawDescOnce.Do(func() {
		file_proto_deck_pocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deck_pocket_proto_rawDesc), len(file_proto_deck_pocket_proto_rawDesc)))
	})
	return file_proto_deck_pocket_proto_rawDescData
}

var file_proto_deck_pocket_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_deck_pocket_proto_goTypes = []any{
	(*GetDeckResquest)(nil), // 0: GetDeckResquest
	(*Request)(nil),         // 1: Request
	(*Response)(nil),        // 2: Response
	(*Card)(nil),            // 3: Card
	(*Pokemon)(nil),         // 4: Pokemon
	(*Ataque)(nil),          // 5: Ataque
	(*Habilidade)(nil),      // 6: Habilidade
	(*Apoiador)(nil),        // 7: Apoiador
	(*Item)(nil),            // 8: Item
	(*Estatistica)(nil),     // 9: Estatistica
}
var file_proto_deck_pocket_proto_depIdxs = []int32{
	3,  // 0: Request.card:type_name -> Card
	9,  // 1: Request.estatistica:type_name -> Estatistica
	3,  // 2: Response.card:type_name -> Card
	9,  // 3: Response.estatistica:type_name -> Estatistica
	4,  // 4: Card.pokemon:type_name -> Pokemon
	8,  // 5: Card.item:type_name -> Item
	7,  // 6: Card.apoiador:type_name -> Apoiador
	5,  // 7: Pokemon.ataque:type_name -> Ataque
	6,  // 8: Pokemon.habilidade:type_name -> Habilidade
	1,  // 9: DeckService.CreateDeck:input_type -> Request
	0,  // 10: DeckService.GetDeck:input_type -> GetDeckResquest
	2,  // 11: DeckService.CreateDeck:output_type -> Response
	2,  // 12: DeckService.GetDeck:output_type -> Response
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_deck_pocket_proto_init() }
func file_proto_deck_pocket_proto_init() {
	if File_proto_deck_pocket_proto != nil {
		return
	}
	file_proto_deck_pocket_proto_msgTypes[3].OneofWrappers = []any{
		(*Card_Pokemon)(nil),
		(*Card_Item)(nil),
		(*Card_Apoiador)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deck_pocket_proto_rawDesc), len(file_proto_deck_pocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deck_pocket_proto_goTypes,
		DependencyIndexes: file_proto_deck_pocket_proto_depIdxs,
		MessageInfos:      file_proto_deck_pocket_proto_msgTypes,
	}.Build()
	File_proto_deck_pocket_proto = out.File
	file_proto_deck_pocket_proto_goTypes = nil
	file_proto_deck_pocket_proto_depIdxs = nil
}
