// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: proto/deck_pocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeckResquest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdDeck        int32                  `protobuf:"varint,1,opt,name=id_deck,json=idDeck,proto3" json:"id_deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckResquest) Reset() {
	*x = GetDeckResquest{}
	mi := &file_proto_deck_pocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckResquest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckResquest) ProtoMessage() {}

func (x *GetDeckResquest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckResquest.ProtoReflect.Descriptor instead.
func (*GetDeckResquest) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeckResquest) GetIdDeck() int32 {
	if x != nil {
		return x.IdDeck
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantidade    int32                  `protobuf:"varint,1,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Tipo          string                 `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Estatistica   *Estatistica           `protobuf:"bytes,3,opt,name=estatistica,proto3" json:"estatistica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_deck_pocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

func (x *Request) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Request) GetEstatistica() *Estatistica {
	if x != nil {
		return x.Estatistica
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Quantidade    int32                  `protobuf:"varint,2,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
	Tipo          string                 `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Card          []*CardResponse        `protobuf:"bytes,4,rep,name=card,proto3" json:"card,omitempty"`
	Estatistica   *Estatistica           `protobuf:"bytes,5,opt,name=estatistica,proto3" json:"estatistica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_deck_pocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Response) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

func (x *Response) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Response) GetCard() []*CardResponse {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *Response) GetEstatistica() *Estatistica {
	if x != nil {
		return x.Estatistica
	}
	return nil
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Pokemon       *Pokemon               `protobuf:"bytes,3,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Item          *Item                  `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	Apoiador      *Apoiador              `protobuf:"bytes,5,opt,name=apoiador,proto3" json:"apoiador,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_proto_deck_pocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{3}
}

func (x *CardResponse) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *CardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardResponse) GetPokemon() *Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *CardResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CardResponse) GetApoiador() *Apoiador {
	if x != nil {
		return x.Apoiador
	}
	return nil
}

type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdDeck        int32                  `protobuf:"varint,1,opt,name=id_deck,json=idDeck,proto3" json:"id_deck,omitempty"`
	Card          []*Card                `protobuf:"bytes,2,rep,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_proto_deck_pocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{4}
}

func (x *AddCardRequest) GetIdDeck() int32 {
	if x != nil {
		return x.IdDeck
	}
	return 0
}

func (x *AddCardRequest) GetCard() []*Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type EditCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdDeck        int32                  `protobuf:"varint,1,opt,name=id_deck,json=idDeck,proto3" json:"id_deck,omitempty"`
	Card          []*Card                `protobuf:"bytes,2,rep,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCardRequest) Reset() {
	*x = EditCardRequest{}
	mi := &file_proto_deck_pocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCardRequest) ProtoMessage() {}

func (x *EditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCardRequest.ProtoReflect.Descriptor instead.
func (*EditCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{5}
}

func (x *EditCardRequest) GetIdDeck() int32 {
	if x != nil {
		return x.IdDeck
	}
	return 0
}

func (x *EditCardRequest) GetCard() []*Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type ResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_proto_deck_pocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseMessage) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	IdPokemon     int32                  `protobuf:"varint,3,opt,name=id_pokemon,json=idPokemon,proto3" json:"id_pokemon,omitempty"`
	IdItem        int32                  `protobuf:"varint,4,opt,name=id_item,json=idItem,proto3" json:"id_item,omitempty"`
	IdApoiador    int32                  `protobuf:"varint,5,opt,name=id_apoiador,json=idApoiador,proto3" json:"id_apoiador,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_deck_pocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{7}
}

func (x *Card) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Card) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Card) GetIdPokemon() int32 {
	if x != nil {
		return x.IdPokemon
	}
	return 0
}

func (x *Card) GetIdItem() int32 {
	if x != nil {
		return x.IdItem
	}
	return 0
}

func (x *Card) GetIdApoiador() int32 {
	if x != nil {
		return x.IdApoiador
	}
	return 0
}

type Pokemon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Tipo          string                 `protobuf:"bytes,4,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Estagio       int32                  `protobuf:"varint,5,opt,name=estagio,proto3" json:"estagio,omitempty"`
	Geracao       int32                  `protobuf:"varint,6,opt,name=geracao,proto3" json:"geracao,omitempty"`
	Ps            int32                  `protobuf:"varint,7,opt,name=ps,proto3" json:"ps,omitempty"`
	Recuo         int32                  `protobuf:"varint,8,opt,name=recuo,proto3" json:"recuo,omitempty"`
	Fraqueza      string                 `protobuf:"bytes,9,opt,name=fraqueza,proto3" json:"fraqueza,omitempty"`
	Ataque        []*Ataque              `protobuf:"bytes,10,rep,name=ataque,proto3" json:"ataque,omitempty"`
	Habilidade    []*Habilidade          `protobuf:"bytes,11,rep,name=habilidade,proto3" json:"habilidade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	mi := &file_proto_deck_pocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{8}
}

func (x *Pokemon) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Pokemon) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Pokemon) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Pokemon) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Pokemon) GetEstagio() int32 {
	if x != nil {
		return x.Estagio
	}
	return 0
}

func (x *Pokemon) GetGeracao() int32 {
	if x != nil {
		return x.Geracao
	}
	return 0
}

func (x *Pokemon) GetPs() int32 {
	if x != nil {
		return x.Ps
	}
	return 0
}

func (x *Pokemon) GetRecuo() int32 {
	if x != nil {
		return x.Recuo
	}
	return 0
}

func (x *Pokemon) GetFraqueza() string {
	if x != nil {
		return x.Fraqueza
	}
	return ""
}

func (x *Pokemon) GetAtaque() []*Ataque {
	if x != nil {
		return x.Ataque
	}
	return nil
}

func (x *Pokemon) GetHabilidade() []*Habilidade {
	if x != nil {
		return x.Habilidade
	}
	return nil
}

type Ataque struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NomeAtaque    string                 `protobuf:"bytes,1,opt,name=nome_ataque,json=nomeAtaque,proto3" json:"nome_ataque,omitempty"`
	DanoAtaque    int32                  `protobuf:"varint,2,opt,name=dano_ataque,json=danoAtaque,proto3" json:"dano_ataque,omitempty"`
	CustoAtaque   string                 `protobuf:"bytes,3,opt,name=custo_ataque,json=custoAtaque,proto3" json:"custo_ataque,omitempty"`
	EfeitoAtaque  string                 `protobuf:"bytes,4,opt,name=efeito_ataque,json=efeitoAtaque,proto3" json:"efeito_ataque,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ataque) Reset() {
	*x = Ataque{}
	mi := &file_proto_deck_pocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ataque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ataque) ProtoMessage() {}

func (x *Ataque) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ataque.ProtoReflect.Descriptor instead.
func (*Ataque) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{9}
}

func (x *Ataque) GetNomeAtaque() string {
	if x != nil {
		return x.NomeAtaque
	}
	return ""
}

func (x *Ataque) GetDanoAtaque() int32 {
	if x != nil {
		return x.DanoAtaque
	}
	return 0
}

func (x *Ataque) GetCustoAtaque() string {
	if x != nil {
		return x.CustoAtaque
	}
	return ""
}

func (x *Ataque) GetEfeitoAtaque() string {
	if x != nil {
		return x.EfeitoAtaque
	}
	return ""
}

type Habilidade struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NomeHabilidade   string                 `protobuf:"bytes,1,opt,name=nome_habilidade,json=nomeHabilidade,proto3" json:"nome_habilidade,omitempty"`
	EfeitoHabilidade string                 `protobuf:"bytes,2,opt,name=efeito_habilidade,json=efeitoHabilidade,proto3" json:"efeito_habilidade,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Habilidade) Reset() {
	*x = Habilidade{}
	mi := &file_proto_deck_pocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Habilidade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habilidade) ProtoMessage() {}

func (x *Habilidade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habilidade.ProtoReflect.Descriptor instead.
func (*Habilidade) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{10}
}

func (x *Habilidade) GetNomeHabilidade() string {
	if x != nil {
		return x.NomeHabilidade
	}
	return ""
}

func (x *Habilidade) GetEfeitoHabilidade() string {
	if x != nil {
		return x.EfeitoHabilidade
	}
	return ""
}

type Apoiador struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Efeito        string                 `protobuf:"bytes,4,opt,name=efeito,proto3" json:"efeito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Apoiador) Reset() {
	*x = Apoiador{}
	mi := &file_proto_deck_pocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Apoiador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Apoiador) ProtoMessage() {}

func (x *Apoiador) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Apoiador.ProtoReflect.Descriptor instead.
func (*Apoiador) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{11}
}

func (x *Apoiador) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Apoiador) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Apoiador) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Apoiador) GetEfeito() string {
	if x != nil {
		return x.Efeito
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome          string                 `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	CardType      string                 `protobuf:"bytes,3,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Efeito        string                 `protobuf:"bytes,4,opt,name=efeito,proto3" json:"efeito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_deck_pocket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{12}
}

func (x *Item) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Item) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Item) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *Item) GetEfeito() string {
	if x != nil {
		return x.Efeito
	}
	return ""
}

type Estatistica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdEstatisca   int32                  `protobuf:"varint,1,opt,name=id_estatisca,json=idEstatisca,proto3" json:"id_estatisca,omitempty"`
	Vitoria       int32                  `protobuf:"varint,2,opt,name=vitoria,proto3" json:"vitoria,omitempty"`
	Derrota       int32                  `protobuf:"varint,3,opt,name=derrota,proto3" json:"derrota,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	PontoGanho    int32                  `protobuf:"varint,5,opt,name=ponto_ganho,json=pontoGanho,proto3" json:"ponto_ganho,omitempty"`
	PontoPerdido  int32                  `protobuf:"varint,6,opt,name=ponto_perdido,json=pontoPerdido,proto3" json:"ponto_perdido,omitempty"`
	MediaPontos   float32                `protobuf:"fixed32,7,opt,name=media_pontos,json=mediaPontos,proto3" json:"media_pontos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Estatistica) Reset() {
	*x = Estatistica{}
	mi := &file_proto_deck_pocket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Estatistica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estatistica) ProtoMessage() {}

func (x *Estatistica) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deck_pocket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estatistica.ProtoReflect.Descriptor instead.
func (*Estatistica) Descriptor() ([]byte, []int) {
	return file_proto_deck_pocket_proto_rawDescGZIP(), []int{13}
}

func (x *Estatistica) GetIdEstatisca() int32 {
	if x != nil {
		return x.IdEstatisca
	}
	return 0
}

func (x *Estatistica) GetVitoria() int32 {
	if x != nil {
		return x.Vitoria
	}
	return 0
}

func (x *Estatistica) GetDerrota() int32 {
	if x != nil {
		return x.Derrota
	}
	return 0
}

func (x *Estatistica) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Estatistica) GetPontoGanho() int32 {
	if x != nil {
		return x.PontoGanho
	}
	return 0
}

func (x *Estatistica) GetPontoPerdido() int32 {
	if x != nil {
		return x.PontoPerdido
	}
	return 0
}

func (x *Estatistica) GetMediaPontos() float32 {
	if x != nil {
		return x.MediaPontos
	}
	return 0
}

var File_proto_deck_pocket_proto protoreflect.FileDescriptor

const file_proto_deck_pocket_proto_rawDesc = "" +
	"\n" +
	"\x17proto/deck_pocket.proto\"*\n" +
	"\x0fGetDeckResquest\x12\x17\n" +
	"\aid_deck\x18\x01 \x01(\x05R\x06idDeck\"m\n" +
	"\aRequest\x12\x1e\n" +
	"\n" +
	"quantidade\x18\x01 \x01(\x05R\n" +
	"quantidade\x12\x12\n" +
	"\x04tipo\x18\x02 \x01(\tR\x04tipo\x12.\n" +
	"\vestatistica\x18\x03 \x01(\v2\f.EstatisticaR\vestatistica\"\xa1\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1e\n" +
	"\n" +
	"quantidade\x18\x02 \x01(\x05R\n" +
	"quantidade\x12\x12\n" +
	"\x04tipo\x18\x03 \x01(\tR\x04tipo\x12!\n" +
	"\x04card\x18\x04 \x03(\v2\r.CardResponseR\x04card\x12.\n" +
	"\vestatistica\x18\x05 \x01(\v2\f.EstatisticaR\vestatistica\"\xa1\x01\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\x12\"\n" +
	"\apokemon\x18\x03 \x01(\v2\b.PokemonR\apokemon\x12\x19\n" +
	"\x04item\x18\x04 \x01(\v2\x05.ItemR\x04item\x12%\n" +
	"\bapoiador\x18\x05 \x01(\v2\t.ApoiadorR\bapoiador\"D\n" +
	"\x0eAddCardRequest\x12\x17\n" +
	"\aid_deck\x18\x01 \x01(\x05R\x06idDeck\x12\x19\n" +
	"\x04card\x18\x02 \x03(\v2\x05.CardR\x04card\"E\n" +
	"\x0fEditCardRequest\x12\x17\n" +
	"\aid_deck\x18\x01 \x01(\x05R\x06idDeck\x12\x19\n" +
	"\x04card\x18\x02 \x03(\v2\x05.CardR\x04card\"-\n" +
	"\x0fResponseMessage\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"\x8c\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\x12\x1d\n" +
	"\n" +
	"id_pokemon\x18\x03 \x01(\x05R\tidPokemon\x12\x17\n" +
	"\aid_item\x18\x04 \x01(\x05R\x06idItem\x12\x1f\n" +
	"\vid_apoiador\x18\x05 \x01(\x05R\n" +
	"idApoiador\"\xa2\x02\n" +
	"\aPokemon\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x12\n" +
	"\x04tipo\x18\x04 \x01(\tR\x04tipo\x12\x18\n" +
	"\aestagio\x18\x05 \x01(\x05R\aestagio\x12\x18\n" +
	"\ageracao\x18\x06 \x01(\x05R\ageracao\x12\x0e\n" +
	"\x02ps\x18\a \x01(\x05R\x02ps\x12\x14\n" +
	"\x05recuo\x18\b \x01(\x05R\x05recuo\x12\x1a\n" +
	"\bfraqueza\x18\t \x01(\tR\bfraqueza\x12\x1f\n" +
	"\x06ataque\x18\n" +
	" \x03(\v2\a.AtaqueR\x06ataque\x12+\n" +
	"\n" +
	"habilidade\x18\v \x03(\v2\v.HabilidadeR\n" +
	"habilidade\"\x92\x01\n" +
	"\x06Ataque\x12\x1f\n" +
	"\vnome_ataque\x18\x01 \x01(\tR\n" +
	"nomeAtaque\x12\x1f\n" +
	"\vdano_ataque\x18\x02 \x01(\x05R\n" +
	"danoAtaque\x12!\n" +
	"\fcusto_ataque\x18\x03 \x01(\tR\vcustoAtaque\x12#\n" +
	"\refeito_ataque\x18\x04 \x01(\tR\fefeitoAtaque\"b\n" +
	"\n" +
	"Habilidade\x12'\n" +
	"\x0fnome_habilidade\x18\x01 \x01(\tR\x0enomeHabilidade\x12+\n" +
	"\x11efeito_habilidade\x18\x02 \x01(\tR\x10efeitoHabilidade\"c\n" +
	"\bApoiador\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x16\n" +
	"\x06efeito\x18\x04 \x01(\tR\x06efeito\"_\n" +
	"\x04Item\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04nome\x18\x02 \x01(\tR\x04nome\x12\x1b\n" +
	"\tcard_type\x18\x03 \x01(\tR\bcardType\x12\x16\n" +
	"\x06efeito\x18\x04 \x01(\tR\x06efeito\"\xe3\x01\n" +
	"\vEstatistica\x12!\n" +
	"\fid_estatisca\x18\x01 \x01(\x05R\vidEstatisca\x12\x18\n" +
	"\avitoria\x18\x02 \x01(\x05R\avitoria\x12\x18\n" +
	"\aderrota\x18\x03 \x01(\x05R\aderrota\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1f\n" +
	"\vponto_ganho\x18\x05 \x01(\x05R\n" +
	"pontoGanho\x12#\n" +
	"\rponto_perdido\x18\x06 \x01(\x05R\fpontoPerdido\x12!\n" +
	"\fmedia_pontos\x18\a \x01(\x02R\vmediaPontos2\xda\x01\n" +
	"\vDeckService\x12!\n" +
	"\n" +
	"CreateDeck\x12\b.Request\x1a\t.Response\x12&\n" +
	"\aGetDeck\x12\x10.GetDeckResquest\x1a\t.Response\x12%\n" +
	"\aAddCard\x12\x0f.AddCardRequest\x1a\t.Response\x12'\n" +
	"\bEditDeck\x12\x10.EditCardRequest\x1a\t.Response\x120\n" +
	"\n" +
	"RemoveDeck\x12\x10.GetDeckResquest\x1a\x10.ResponseMessageB\aZ\x05go/pbb\x06proto3"

var (
	file_proto_deck_pocket_proto_rawDescOnce sync.Once
	file_proto_deck_pocket_proto_rawDescData []byte
)

func file_proto_deck_pocket_proto_rawDescGZIP() []byte {
	file_proto_deck_pocket_proto_rawDescOnce.Do(func() {
		file_proto_deck_pocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deck_pocket_proto_rawDesc), len(file_proto_deck_pocket_proto_rawDesc)))
	})
	return file_proto_deck_pocket_proto_rawDescData
}

var file_proto_deck_pocket_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_deck_pocket_proto_goTypes = []any{
	(*GetDeckResquest)(nil), // 0: GetDeckResquest
	(*Request)(nil),         // 1: Request
	(*Response)(nil),        // 2: Response
	(*CardResponse)(nil),    // 3: CardResponse
	(*AddCardRequest)(nil),  // 4: AddCardRequest
	(*EditCardRequest)(nil), // 5: EditCardRequest
	(*ResponseMessage)(nil), // 6: ResponseMessage
	(*Card)(nil),            // 7: Card
	(*Pokemon)(nil),         // 8: Pokemon
	(*Ataque)(nil),          // 9: Ataque
	(*Habilidade)(nil),      // 10: Habilidade
	(*Apoiador)(nil),        // 11: Apoiador
	(*Item)(nil),            // 12: Item
	(*Estatistica)(nil),     // 13: Estatistica
}
var file_proto_deck_pocket_proto_depIdxs = []int32{
	13, // 0: Request.estatistica:type_name -> Estatistica
	3,  // 1: Response.card:type_name -> CardResponse
	13, // 2: Response.estatistica:type_name -> Estatistica
	8,  // 3: CardResponse.pokemon:type_name -> Pokemon
	12, // 4: CardResponse.item:type_name -> Item
	11, // 5: CardResponse.apoiador:type_name -> Apoiador
	7,  // 6: AddCardRequest.card:type_name -> Card
	7,  // 7: EditCardRequest.card:type_name -> Card
	9,  // 8: Pokemon.ataque:type_name -> Ataque
	10, // 9: Pokemon.habilidade:type_name -> Habilidade
	1,  // 10: DeckService.CreateDeck:input_type -> Request
	0,  // 11: DeckService.GetDeck:input_type -> GetDeckResquest
	4,  // 12: DeckService.AddCard:input_type -> AddCardRequest
	5,  // 13: DeckService.EditDeck:input_type -> EditCardRequest
	0,  // 14: DeckService.RemoveDeck:input_type -> GetDeckResquest
	2,  // 15: DeckService.CreateDeck:output_type -> Response
	2,  // 16: DeckService.GetDeck:output_type -> Response
	2,  // 17: DeckService.AddCard:output_type -> Response
	2,  // 18: DeckService.EditDeck:output_type -> Response
	6,  // 19: DeckService.RemoveDeck:output_type -> ResponseMessage
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_deck_pocket_proto_init() }
func file_proto_deck_pocket_proto_init() {
	if File_proto_deck_pocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deck_pocket_proto_rawDesc), len(file_proto_deck_pocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deck_pocket_proto_goTypes,
		DependencyIndexes: file_proto_deck_pocket_proto_depIdxs,
		MessageInfos:      file_proto_deck_pocket_proto_msgTypes,
	}.Build()
	File_proto_deck_pocket_proto = out.File
	file_proto_deck_pocket_proto_goTypes = nil
	file_proto_deck_pocket_proto_depIdxs = nil
}
